# .pre-commit-config.yaml
# One Python version for every hook (override only when a tool demands it)
default_language_version:
  python: python3.12        # upper end of the project's python constraint

repos:
  # ── Ruff: lint (auto-fix) then format ────────────────────────────────────────
  - repo: https://github.com/astral-sh/ruff
    rev: v0.5.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy          # `strict = true` already lives in pyproject.toml
        # args: [--strict]   # optional / redundant

  # ── Bandit: security scan, reads pyproject.toml ─────────────────────────────
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args:
          [
            "-c", "pyproject.toml",          # tell Bandit to load TOML config
            "--severity-level", "MEDIUM",
            "--confidence-level", "MEDIUM",
            "-r", "src/faa_sc_filler/",      # scan the actual source tree
          ]
        additional_dependencies: ["bandit[toml]"]   # enables TOML parsing :contentReference[oaicite:0]{index=0}

  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.7.2
    hooks:
      - id: pip-audit
        # Poetry keeps deps in pyproject.toml, so audit that file
        args: ["-r", "pyproject.toml"]

  # ── Local test runner ────────────────────────────────────────────────────────
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
