[tool.poetry]
name = "faa-sc-filler"
version = "0.1.0"
description = "FAA Special Conditions Template Filler"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "faa_sc_filler", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<=3.12.1"
python-docx = "^1.0.0"
gradio = "^3.50.2"  # Downgrade to 3.x series
rich = "^13.7.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-asyncio = "^0.23.5"
pytest-cov = "^4.1.0"
black = "^23.12.1"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
faa-sc-filler = "faa_sc_filler.cli:main"

[tool.pytest.ini_options]
asyncio_mode = "strict"
markers = [
    "asyncio: mark test as async/await test"
]
