[tool.poetry]
name = "faa-sc-filler"
version = "0.1.0"
description = "FAA Special Conditions Template Filler"
authors = ["OpenAI <info@openai.com>"]
readme = "README.md"
packages = [{include = "faa_sc_filler", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<=3.12.1"
python-docx = "^1.0.0"
gradio = "^3.50.2"  # Downgrade to 3.x series
rich = "^13.7.0"
python-dateutil = "^2.8.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-asyncio = "^0.23.5"
pytest-cov = "^5.0.0"
coverage = "^7.5.0"
hypothesis = "^6.0.0"
black = "^24.4.2"
ruff = "^0.5.0"
mypy = "^1.10.0"
bandit = "^1.9.0"
pre-commit = "^3.7.0"
pip-audit = "^2.6.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
faa-sc-filler = "faa_sc_filler.cli:main"

[tool.pytest.ini_options]
asyncio_mode = "strict"
markers = [
    "asyncio: mark test as async/await test"
]
