[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "faa-sc-filler"
version = "1.0.0"
description = "FAA Special Conditions Template Filler"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-docx>=1.1.2",
    "gradio>=4.16",
    "python-dateutil",
    "rich"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["faa_sc_filler*"]
namespaces = false

[tool.setuptools.package-data]
faa_sc_filler = ["py.typed"]
