name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Type check
        run: mypy src/ --strict
      - name: Test
        run: |
          pytest --cov=src --cov-report=term-missing
          coverage report --fail-under=90
      - name: Security scan
        run: |
          bandit -r src/ -f json -o bandit-report.json
          pip-audit -r requirements.txt
